export const HTTP_CREATED = 201
export const HTTP_OK = 200
export const HTTP_UNAUTHORIZED = 401
export const HTTP_UNPROCESSABLE_ENTITY = 422
export const HTTP_PAGE_EXPIRED = 419
export const HTTP_INTERNAL_SERVER_ERROR = 500